services:
  backend:
    image: alexriviere/dockerdemo:backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    image: alexriviere/dockerdemo:frontend-v3
    ports:
      - "3000:3000"
    depends_on:
      - backend